# Generated by Django 4.0.3 on 2022-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds_app', '0005_alter_birds_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
